server:
  port: ${SERVER_PORT}

spring:
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  redis:
    #database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
    timeout: 3000 # 连接超时时间（毫秒）
  cloud:
    sentinel:
      enabled: true #是否开启，默认true
      eager: true #是否饥饿加载，默认false
      transport:
        dashboard: ${SENTINEL_DASHBOARD} #sentinel控制台地址
      filter:
        url-patterns: /** #拦截请求地址
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: ${SENTINEL_NACOS_SERVER} # Nacos 服务器地址
            namespace: ${SENTINEL_NACOS_NAMESPACE} # Nacos 命名空间
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型

dubbo:
  scan:
    base-packages: com.pueeo.post.service
  protocol:
    name: dubbo
    port: -1
  #注册中心配置
  registry:
    address: spring-cloud://${DUBBO_REGISTRY_ADDRESS}
  cloud:
    subscribed-services: '' #设置订阅的应用列表，默认为* 订阅所有应用, ''则不订阅
  consumer:
    check: false #为false表示启动时不检查是否有消费者
    filter: userContextConsumerFilter
  #自定义filter
  provider:
    filter: dubboExceptionFilter,-exception,userContextProviderFilter #使用自定义Filter，禁用默认的ExceptionFilter