spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      enabled: true #是否开启，默认true
      eager: true #是否饥饿加载，默认false
      transport:
        dashboard: ${SENTINEL_DASHBOARD} #sentinel控制台地址
      filter:
        url-patterns: /** #拦截请求地址
      # Sentinel 规则的数据源，是一个 Map 类型。key 为数据源名，可自定义；value 为数据源的具体配置
      datasource:
        ds1:
          # 对应 DataSourcePropertiesConfiguration 类
          nacos:
            server-addr: ${SENTINEL_NACOS_SERVER} # Nacos 服务器地址
            namespace: ${SENTINEL_NACOS_NAMESPACE} # Nacos 命名空间
            data-id: ${spring.application.name}-flow-rule # Nacos 配置集编号
            data-type: json # 数据格式
            rule-type: FLOW # 规则类型



dubbo:
  #指定Dubbo服务实现类的扫描基准包
  scan:
    base-packages: com.pueeo.user.service
  #协议配置
  protocol:
    name: dubbo
    port: -1 #协议端口，-1表示自增端口，从20880开始
  #注册中心配置
  registry:
    address: spring-cloud://${DUBBO_REGISTRY_ADDRESS}
  cloud:
    subscribed-services: '' #设置订阅的应用列表，默认为* 订阅所有应用, ''则不订阅
  consumer:
    check: false #为false表示启动时不检查是否有消费者
  #自定义filter
  provider:
    filter: dubboExceptionFilter,-exception #使用自定义Filter，禁用默认的ExceptionFilter
