spring:
  application:
    name: mycloud-flow
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.112.127.20
        namespace: 44f6ce99-f0ad-4cef-8b37-9bb33c92a2f4

dubbo:
  scan:
    base-packages: com.pueeo.flow.service
  protocol:
    name: dubbo
    port: -1
  #注册中心配置
  registry:
    address: spring-cloud://47.112.127.20:8848
  cloud:
    subscribed-services: mycloud-user # 设置订阅的应用列表，默认为* 订阅所有应用, ''则不订阅
  consumer:
    check: false #为false表示启动时不检查是否有消费者
